---
okta:
  oauth2:
    issuer: https://positivelytonya.okta.com
    client-id: 0oa168j5sq2qM4vn24x7
    client-secret: pz-BoQ5NUN824_j6k5-7dBtxnmJR9PnO_GH5cYpu
provider:
  otka:
    authorization-uri: https://positivelytonya.okta.com/oauth2/default/v1/authorize
    token-uri: https://oauth2/default/v1/token
    user-info-uri: https://positivelytonya.okta.com/oauth2/default/v1/userinfo
    jwk-set-uri: https://positivelytonya.okta.com/oauth2/default/v1/keys

spring:
  data:
    rest:
      basePath: api
